using System.Text;
using Klocman.Tools;
using UninstallTools;

namespace BcuCli;

/// <summary>
/// Extra export formats beyond JSON/CSV (native BCU XML list, batch and PowerShell
/// uninstall scripts) and loading a previously saved BCU list.
/// </summary>
public static class Exporters
{
    /// <summary>
    /// Handle the export formats that aren't plain JSON/CSV. Returns true if this
    /// exporter handled the format, false if the caller should fall back to JSON/CSV.
    /// </summary>
    public static bool TryExport(IList<ApplicationUninstallerEntry> apps, CliArgs args)
    {
        switch (args.Format)
        {
            case OutputFormat.Xml:
                ExportXml(apps, args);
                return true;
            case OutputFormat.Bat:
                ExportScript(apps, args, powershell: false);
                return true;
            case OutputFormat.Ps1:
                ExportScript(apps, args, powershell: true);
                return true;
            default:
                return false;
        }
    }

    // Native BCU list format (XML). ApplicationEntrySerializer writes directly to a file,
    // so an --output path is mandatory.
    private static void ExportXml(IList<ApplicationUninstallerEntry> apps, CliArgs args)
    {
        if (string.IsNullOrEmpty(args.OutputFile))
            throw new ArgumentException("--format xml requires --output <file> (the serializer writes a file directly).");

        ApplicationEntrySerializer.SerializeApplicationEntries(args.OutputFile, apps);
        if (!args.Quiet)
            Console.Error.WriteLine($"Wrote BCU list ({apps.Count} entries) to {args.OutputFile}");
    }

    // Generate a runnable uninstall script. Prefers the quiet uninstall string so the
    // script can run unattended; falls back to the normal uninstall string.
    private static void ExportScript(IList<ApplicationUninstallerEntry> apps, CliArgs args, bool powershell)
    {
        var sb = new StringBuilder();
        if (powershell)
        {
            sb.AppendLine("# Uninstall script generated by bcu-cli");
            sb.AppendLine("# Review before running. Run elevated.");
            sb.AppendLine("$ErrorActionPreference = 'Continue'");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("@echo off");
            sb.AppendLine("REM Uninstall script generated by bcu-cli");
            sb.AppendLine("REM Review before running. Run elevated.");
            sb.AppendLine();
        }

        int written = 0;
        foreach (var e in apps)
        {
            var cmd = e.QuietUninstallPossible ? e.QuietUninstallString : e.UninstallString;
            if (string.IsNullOrWhiteSpace(cmd)) continue;
            written++;

            if (powershell)
            {
                sb.AppendLine($"Write-Host 'Uninstalling: {EscapePsSingle(e.DisplayName ?? "")}'");
                sb.AppendLine($"Start-Process -Wait -FilePath cmd.exe -ArgumentList '/c', \"{EscapePsDouble(cmd)}\"");
                sb.AppendLine();
            }
            else
            {
                sb.AppendLine($"echo Uninstalling: {e.DisplayName}");
                sb.AppendLine(cmd);
                sb.AppendLine();
            }
        }

        var ext = powershell ? "ps1" : "bat";
        if (!string.IsNullOrEmpty(args.OutputFile))
        {
            File.WriteAllText(args.OutputFile, sb.ToString(), powershell ? new UTF8Encoding(true) : Encoding.ASCII);
            if (!args.Quiet)
                Console.Error.WriteLine($"Wrote {written} uninstall command(s) to {args.OutputFile} ({ext})");
        }
        else
        {
            Console.Out.Write(sb.ToString());
        }
    }

    // bcu import-list <file> — load a saved BCU XML list and render it like 'list'.
    public static int RunImportList(CliArgs args)
    {
        if (string.IsNullOrWhiteSpace(args.ImportFile))
        {
            Console.Error.WriteLine("Usage: bcu import-list <file.xml> [--format table|json|csv]");
            return 1;
        }
        if (!File.Exists(args.ImportFile))
        {
            Console.Error.WriteLine($"File not found: {args.ImportFile}");
            return 1;
        }

        List<ApplicationUninstallerEntry> items;
        try
        {
            var data = SerializationTools.DeserializeFromXml<ApplicationEntrySerializer>(args.ImportFile);
            items = data?.Items ?? new List<ApplicationUninstallerEntry>();
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Failed to read BCU list: {ex.Message}");
            return 1;
        }

        if (!args.Quiet)
            Console.Error.WriteLine($"Loaded {items.Count} entries from {args.ImportFile}");

        switch (args.Format)
        {
            case OutputFormat.Json:
                using (var w = Output.OpenOutput(args)) Output.PrintJson(items, args.VerifyCerts, w ?? Console.Out);
                break;
            case OutputFormat.Csv:
                using (var w = Output.OpenOutput(args)) Output.PrintCsv(items, args.VerifyCerts, w ?? Console.Out);
                break;
            default:
                Output.PrintTable(items, args.Wide, args.VerifyCerts);
                break;
        }
        return 0;
    }

    private static string EscapePsSingle(string s) => s.Replace("'", "''");
    private static string EscapePsDouble(string s) => s.Replace("\"", "`\"");
}
